import React from "react";
import { assets } from "./assets/assets";

export const data = {
  popular: [
    {
      id: 1,
      image: assets.eventContent.Event1,
      title: "Let you go insane",
      day: "Tuesday",
      date: "22nd January 2024",
      time: "22:00",
      location: "1901 Thornridge Cir. Shiloh, Hawaii 81063",
      username: "Annette Black",
      followers: "23.5k",
      attendance: "200 people are attending this event.",
      content:
        "Lorem ipsum dolor sit amet consectetur. Sit massa et faucibus cursus integer aenean sed sed. Aliquet mi magna viverra amet. Malesuada neque in tellus velit. Quisque sapien pellentesque sed interdum euismod. Donec commodo laoreet amet at hac nec. Egestas tincidunt dolor nibh amet lectus duis commodo. Ac pretium nulla tellus.",
    },
    {
      id: 2,
      image: assets.eventContent.Event2,
      title: "We The Tribals",
      day: "Friday",
      date: "25th January 2024",
      time: "19:00",
      location: "4140 Parker Rd, Allentown, New Mexico 31134",
      username: "Arlene McCoy",
      followers: "23.5k",
      attendance: "200 people are attending this event.",
      content:
        "Lorem ipsum dolor sit amet consectetur. Sit massa et faucibus cursus integer aenean sed sed. Aliquet mi magna viverra amet. Malesuada neque in tellus velit. Quisque sapien pellentesque sed interdum euismod. Donec commodo laoreet amet at hac nec. Egestas tincidunt dolor nibh amet lectus duis commodo. Ac pretium nulla tellus.",
    },
    {
      id: 3,
      image: assets.eventContent.Event3,
      title: "Join Us For Humanity",
      day: "Tuesday",
      date: "27th February",
      time: "18:00",
      location: "3891 Ranchview Dr. Richardson, California 62639",
      username: "Marvin McKinney",
      followers: "23.5k",
      attendance: "200 people are attending this event.",
      content:
        "Lorem ipsum dolor sit amet consectetur. Sit massa et faucibus cursus integer aenean sed sed. Aliquet mi magna viverra amet. Malesuada neque in tellus velit. Quisque sapien pellentesque sed interdum euismod. Donec commodo laoreet amet at hac nec. Egestas tincidunt dolor nibh amet lectus duis commodo. Ac pretium nulla tellus.",
    },
    {
      id: 4,
      image: assets.eventContent.Event4,
      title: "Save Earth",
      day: "Tuesday",
      date: "27th February",
      time: "18:00",
      location: "3517 W. Gray St. Utica, Pennsylvania 57867",
      username: "Jacob Jones",
      followers: "23.5k",
      attendance: "200 people are attending this event.",
      content:
        "Lorem ipsum dolor sit amet consectetur. Sit massa et faucibus cursus integer aenean sed sed. Aliquet mi magna viverra amet. Malesuada neque in tellus velit. Quisque sapien pellentesque sed interdum euismod. Donec commodo laoreet amet at hac nec. Egestas tincidunt dolor nibh amet lectus duis commodo. Ac pretium nulla tellus.",
    },
    {
      id: 5,
      image: assets.eventContent.Event5,
      title: "Linkin Park Celebration Party",
      day: "Sunday",
      date: "14th February",
      time: "23:00",
      location: "3517 W. Gray St. Utica, Pennsylvania 57867",
      username: "Jerome Bell",
      followers: "23.5k",
      attendance: "200 people are attending this event.",
      content:
        "Lorem ipsum dolor sit amet consectetur. Sit massa et faucibus cursus integer aenean sed sed. Aliquet mi magna viverra amet. Malesuada neque in tellus velit. Quisque sapien pellentesque sed interdum euismod. Donec commodo laoreet amet at hac nec. Egestas tincidunt dolor nibh amet lectus duis commodo. Ac pretium nulla tellus.",
    },
    {
      id: 6,
      image: assets.eventContent.Event6,
      title: "Together stronger!",
      day: "Friday",
      date: "15th December 2023",
      time: "12:00",
      location: "4517 Washington Ave. Manchester, Kentucky 39495",
      username: "Guy Hawkins",
      followers: "23.5k",
      attendance: "200 people are attending this event.",
      content:
        "Lorem ipsum dolor sit amet consectetur. Sit massa et faucibus cursus integer aenean sed sed. Aliquet mi magna viverra amet. Malesuada neque in tellus velit. Quisque sapien pellentesque sed interdum euismod. Donec commodo laoreet amet at hac nec. Egestas tincidunt dolor nibh amet lectus duis commodo. Ac pretium nulla tellus.",
    },
    {
      id: 7,
      image: assets.eventContent.Event7,
      title: "We celebrate the dead ",
      day: "Sunday",
      date: "14th February 2023",
      time: "23:00",
      location: "4517 Washington Ave. Manchester, Kentucky 39495",
      username: "Courtney Henry",
      followers: "23.5k",
      attendance: "200 people are attending this event.",
      content:
        "Lorem ipsum dolor sit amet consectetur. Sit massa et faucibus cursus integer aenean sed sed. Aliquet mi magna viverra amet. Malesuada neque in tellus velit. Quisque sapien pellentesque sed interdum euismod. Donec commodo laoreet amet at hac nec. Egestas tincidunt dolor nibh amet lectus duis commodo. Ac pretium nulla tellus.",
    },
    {
      id: 8,
      image: assets.eventContent.Event8,
      title: "Food Life",
      day: "Tuesday",
      date: "27th February",
      time: "18:00",
      location: "8502 Preston Rd. Inglewood, Maine 98380",
      username: "Esther Howard",
      followers: "23.5k",
      attendance: "200 people are attending this event.",
      content:
        "Lorem ipsum dolor sit amet consectetur. Sit massa et faucibus cursus integer aenean sed sed. Aliquet mi magna viverra amet. Malesuada neque in tellus velit. Quisque sapien pellentesque sed interdum euismod. Donec commodo laoreet amet at hac nec. Egestas tincidunt dolor nibh amet lectus duis commodo. Ac pretium nulla tellus.",
    },
  ],

  moreEvents: [
    {
      id: 9,
      image: assets.eventContent.Event9,
      title: "Join Me: Birthday Party",
      day: "Tuesday",
      date: "22nd January 2024",
      time: "22:00",
      location: "1901 Thornridge Cir. Shiloh, Hawaii 81063",
      username: "Annette Black",
      followers: "23.5k",
      attendance: "200 people are attending this event.",
      content:
        "Lorem ipsum dolor sit amet consectetur. Sit massa et faucibus cursus integer aenean sed sed. Aliquet mi magna viverra amet. Malesuada neque in tellus velit. Quisque sapien pellentesque sed interdum euismod. Donec commodo laoreet amet at hac nec. Egestas tincidunt dolor nibh amet lectus duis commodo. Ac pretium nulla tellus.",
    },
    {
      id: 10,
      image: assets.eventContent.Event10,
      title: "Freedom March: Join our hands",
      day: "Friday",
      date: "25th January 2024",
      time: "19:00",
      location: "4140 Parker Rd. Allentown, New Mexico 31134",
      username: "Arlene McCoy",
      followers: "23.5k",
      attendance: "200 people are attending this event.",
      content:
        "Lorem ipsum dolor sit amet consectetur. Sit massa et faucibus cursus integer aenean sed sed. Aliquet mi magna viverra amet. Malesuada neque in tellus velit. Quisque sapien pellentesque sed interdum euismod. Donec commodo laoreet amet at hac nec. Egestas tincidunt dolor nibh amet lectus duis commodo. Ac pretium nulla tellus.",
    },
    {
      id: 11,
      image: assets.eventContent.Event11,
      title: "FStop Wars Petition Signing",
      day: "Tuesday",
      date: "27th February",
      time: "18:00",
      location: "3891 Ranchview Dr. Richardson, California 62639",
      username: "Marvin McKinney",
      followers: "23.5k",
      attendance: "200 people are attending this event.",
      content:
        "Lorem ipsum dolor sit amet consectetur. Sit massa et faucibus cursus integer aenean sed sed. Aliquet mi magna viverra amet. Malesuada neque in tellus velit. Quisque sapien pellentesque sed interdum euismod. Donec commodo laoreet amet at hac nec. Egestas tincidunt dolor nibh amet lectus duis commodo. Ac pretium nulla tellus.",
    },
    {
      id: 12,
      image: assets.eventContent.Event12,
      title: "The Weeknd: Starboy",
      day: "Tuesday",
      date: "27th February",
      time: "18:00",
      location: "3517 W. Gray St. Utica, Pennsylvania 57867",
      username: "Jacob Jones",
      followers: "23.5k",
      attendance: "200 people are attending this event.",
      content:
        "Lorem ipsum dolor sit amet consectetur. Sit massa et faucibus cursus integer aenean sed sed. Aliquet mi magna viverra amet. Malesuada neque in tellus velit. Quisque sapien pellentesque sed interdum euismod. Donec commodo laoreet amet at hac nec. Egestas tincidunt dolor nibh amet lectus duis commodo. Ac pretium nulla tellus.",
    },
    {
      id: 13,
      image: assets.eventContent.Event13,
      title: "Labrinth: Home Tour",
      day: "Sunday",
      date: "14th February",
      time: "23:00",
      location: "3517 W. Gray St. Utica, Pennsylvania 57867",
      username: "Jerome Bell",
      followers: "23.5k",
      attendance: "200 people are attending this event.",
      content:
        "Lorem ipsum dolor sit amet consectetur. Sit massa et faucibus cursus integer aenean sed sed. Aliquet mi magna viverra amet. Malesuada neque in tellus velit. Quisque sapien pellentesque sed interdum euismod. Donec commodo laoreet amet at hac nec. Egestas tincidunt dolor nibh amet lectus duis commodo. Ac pretium nulla tellus.",
    },
    {
      id: 14,
      image: assets.eventContent.Event14,
      title: "We Are One Tour",
      day: "Friday",
      date: "15th December 2023",
      time: "12:00",
      location: "4517 Washington Ave. Manchester, Kentucky 39495",
      username: "Guy Hawkins",
      followers: "23.5k",
      attendance: "200 people are attending this event.",
      content:
        "Lorem ipsum dolor sit amet consectetur. Sit massa et faucibus cursus integer aenean sed sed. Aliquet mi magna viverra amet. Malesuada neque in tellus velit. Quisque sapien pellentesque sed interdum euismod. Donec commodo laoreet amet at hac nec. Egestas tincidunt dolor nibh amet lectus duis commodo. Ac pretium nulla tellus.",
    },
    {
      id: 15,
      image: assets.eventContent.Event15,
      title: "Trust Foundation: Care for heart march",
      day: "Sunday",
      date: "14th February",
      time: "23:00",
      location: "4517 Washington Ave. Manchester, Kentucky 39495",
      username: "Courtney Henry",
      followers: "23.5k",
      attendance: "200 people are attending this event.",
      content:
        "Lorem ipsum dolor sit amet consectetur. Sit massa et faucibus cursus integer aenean sed sed. Aliquet mi magna viverra amet. Malesuada neque in tellus velit. Quisque sapien pellentesque sed interdum euismod. Donec commodo laoreet amet at hac nec. Egestas tincidunt dolor nibh amet lectus duis commodo. Ac pretium nulla tellus.",
    },
    {
      id: 16,
      image: assets.eventContent.Event16,
      title: "Mom’s Kitchen",
      day: "Tuesday",
      date: "27th February",
      time: "18:00",
      location: "8502 Preston Rd. Inglewood, Maine 98380",
      username: "Esther Howard",
      followers: "23.5k",
      attendance: "200 people are attending this event.",
      content:
        "Lorem ipsum dolor sit amet consectetur. Sit massa et faucibus cursus integer aenean sed sed. Aliquet mi magna viverra amet. Malesuada neque in tellus velit. Quisque sapien pellentesque sed interdum euismod. Donec commodo laoreet amet at hac nec. Egestas tincidunt dolor nibh amet lectus duis commodo. Ac pretium nulla tellus.",
    },
  ],

  testimonials: [
    {
      id: 17,
      image: assets.avatars.brooklynSimons,
      name: "Brooklyn Simons",
      title: "(VP, Xiaomi Cameroon)",
      content:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    },
    {
      id: 18,
      image: assets.avatars.guyHawkins,
      name: "Guy Hawkins",
      title: "(Judge, India’s Got Talent)",
      content:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    },
    {
      id: 19,
      image: assets.avatars.bessieCooper,
      name: "Bessie Cooper",
      title: "(Singer, Brazilia Broskies)",
      content:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    },
  ],

  tickets: [
    {
      id: 20,
      image: assets.tickets.ticket1,
      eventName: "Music Party with Special Guest",
      address: "1901 Thornridge Cir. Shiloh, Hawaii 81063",
      day: "Friday",
      date: "25th January 2024",
      quantity: 2,
    },
    {
      id: 21,
      image: assets.tickets.ticket2,
      eventName: "Join Us! Christmas Party ",
      address: "2715 Ash Dr. San Jose, South Dakota 83475",
      day: "Saturday",
      date: "18th January 2024",
      quantity: 2,
    },
    {
      id: 22,
      image: assets.tickets.ticket3,
      eventName: "Food Court Special",
      address: "6391 Elgin St. Celina, Delaware 10299",
      day: "Friday",
      date: "17th January 2024",
      quantity: 2,
    },
    {
      id: 23,
      image: assets.tickets.ticket4,
      eventName: "We are foodies! Prepare and eat",
      address: "2118 Thornridge Cir. Syracuse, Connecticut 35624",
      day: "Wednesday",
      date: "12th January 2024",
      quantity: 2,
    },
    {
      id: 24,
      image: assets.tickets.ticket5,
      eventName: "Physics Bootcamp ‘2024",
      address: "8502 Preston Rd. Inglewood, Maine 98380",
      day: "Wednesday",
      date: "12th January 2024",
      quantity: 1,
    },
    {
      id: 25,
      image: assets.tickets.ticket6,
      eventName: "BWF Live World Cup Screening",
      address: "3517 W. Gray St. Utica, Pennsylvania 57867",
      day: "Wednesday",
      date: "12th January 2024",
      quantity: 1,
    },
    {
      id: 26,
      image: assets.tickets.ticket7,
      eventName: "Wimbledon Live Screening",
      address: "4517 Washington Ave. Manchester, Kentucky 39495",
      day: "Tuesday",
      date: "18th January 2024",
      quantity: 2,
    },
    {
      id: 27,
      image: assets.tickets.ticket8,
      eventName: "Year End Festival",
      address: "2464 Royal Ln. Mesa, New Jersey 45463",
      day: "Friday",
      date: "25th June 2024",
      quantity: 2,
    },
  ],
};
